### ISSUE TITLE
[FEATURE REQUEST] Make armor values of alfsteel armor modifiable via config

### ISSUE THREAD

**Issue by BennetBfkg** [noeppi-noeppi/MythicBotany#114]
As title says, for balancing purposes I would like to change these values

**Comment by noeppi-noeppi** [comment]
> Also wouldn't mind an option where it requires mana to use the ranged attack since that would make sense.

It does require mana. However that mana is taken from its durability, just like it's done with the terra blade.

> Want it in a pack I'm making but my only option at the moment is to remove the mod.

What do you want to achieve with that? Well it sounds like your goal is to "force" me to add the config option. In that case: Do you really think, modders make mods for people to put them in a modpack? Do you think, my primary goal is to have my mods in as many modpacks as possible, and thus, I'll do anything for a modpack developer to get my mod in?

I have do disillusion you here. I make mods, because I enjoy making mods. And modpack makers should make modpacks because they enjoy making modpacks. Of course, if there is a feature that would be useful for a modpack, don't bother asking about it. Asking, however is fundamentally different from threatening with removal of the mod from your pack.

So don't expect anyone (including me) to care about that. I do care about feature requests that would make my mod better. And if they help a modpack maker as well, that's even better. But threatening with mod removal is definitely the wrong way.
