### ISSUE TITLE
Crash while trying to add Apotheosis affix to Mjoelnir

### ISSUE THREAD

**Issue by Zarvera** [noeppi-noeppi/MythicBotany#122]
This is, of course, not neccessarily Mythic Botany's fault, but considering so far it only ever happened to Mjoelnir i'll try you guys first.
What happens is when you put Mjoelnir into the reforge table from Apotheosis and add ingredients so that it displays 3 possible affix combinations, hovering cursor over any of them crashes instance.
Crash is a doozy, too:
https://controlc.com/93f6142d

**Comment by noeppi-noeppi** [comment]
Happens because of [this](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.19/src/main/java/shadows/apotheosis/mixin/EnchantmentHelperMixin.java#L74-L82) mixin calling [LootCategory.forItem](https://github.com/Shadows-of-Fire/Apotheosis/blob/f4b8785dada0dbc8b5dc05b0730e005571afe82e/src/main/java/shadows/apotheosis/adventure/loot/LootCategory.java#L54-L61) on mjöllnir. The `SWORD` loot category then check the attribute modifiers to check whether something counts as sword.

However, the code that computes the mjöllnir attribute modifiers calls `EnchantmentHelper.getDamageBonus` which causes an infinite loop.

I don't see a good way to fix this in MythicBotany. Apotheosis is doing the mixin here and I think they should fix the problem.

Another
