### ISSUE TITLE
BLOCKS UNBREAKABLE Botania Additions Gaia Ring of Aura Alf Shatterer not working together 

### ISSUE THREAD

**Issue by SugarDaddii** [noeppi-noeppi/MythicBotany#134]
When i equippt Ring of Aura and Alf Shatterer i cannot Break any Blocks.

Dev of Botania Additions says: 

"this bug is on the devs of the alf shatterer.
The reason is - they do not implement shouldCauseReequipAnimation method, which prevents reequip animation AND resetting block break progress."

**Comment by noeppi-noeppi** [comment]
The alf shatterer inherits `shouldCauseReequipAnimation` from `TerraShattererItem`, so saying it doesn't implement this method is just wrong. The actual issue is that Botanic Additions does not add its aura ring to the `botania:terra_pick_blacklist` tag.

I did a quick test: Adding a datapack that adds the Gaia Ring of Aura to this tag fixes the issue. Please contact the developer of Botanic Additions and ask them to fix this.
