### ISSUE TITLE
Mana Infuser costs not clear

### ISSUE THREAD

**Issue by Serifina** [noeppi-noeppi/MythicBotany#28]
Based on what's shown in the Lexica Botania and JEI, the Mana Infuser should have an inherent 1/4 cost on making Terrasteel on Alfsteel - so that it makes Terrasteel at the cost of 12.5% of a mana pool, and Alfsteel at the cost of 50% of a mana pool.

Right now, that doesn't seem to be working - using a Mana Infuser, Terrasteel still costs the normal 50% of a mana pool, and Alfsteel takes a whopping _two_ Mana Pools.

**Comment by noeppi-noeppi** [comment]
I've heard that several times now but actually it is intended. I scale the mana bar down to fit higher mana costs into it.
Suggestions on how to display this better are appreciated, however I will not put a second mana bar below the first one.

**Comment by Fugiman** [comment]
Heya, I was the player who originally had the confusion around cost. I was treating the Lexica Botanica as the authority (rather than JEI). In all vanilla Botania recipes 1 bar is worth 1 mana pool, sometimes with a 10x zoom applied (and a note under the bar). I think this is the source of confusion: Botania players are trained by Botania to treat a bar as 1 mana pool and then are surprised when MythicBotany changes it to represent 8 mana pools.

A couple options off the top of my head:
1. Keep the mana bars, change them to be 1 mana pool, have the Alfsteel Ingot have two full bars stacked vertically. I understand you said you didn't want to do this, but wanted to include it for completeness as it is the most visually straightforward change (though potentially complicated code-wise).
2. Keep the mana bars, change them to be 1 mana pool, have the Alfsteel Ingot have two full bars arranged horizontally. This is basically the same as 1 but if the complexity code-wise was simply vertical space then this avoids it and should look acceptable.
3. Change the zoom on the mana bars from 10x/1x to 1x/0.25x. This makes it clear to users that the scale of the bar has been changed so long as they notice the different zoom text.
4. Remove the mana bars entirely. This is actually how Terrasteel Ingots work currently in the Lexica Botanica, rather than having a mana bar in the recipe it just explains in the text of the book that "The infusion uses about half a Mana Pool's worth of Mana to create a single piece of Terrasteel".

Overall I expect 4 to be the simplest to implement and should remove all the confusion I experienced, but I'll leave it to you as the mod author to figure out how you want to do it. I hope my ideas were helpful :)

**Comment by noeppi-noeppi** [comment]
I think I'll go for 3 and give the mana bar a slightly different colour so it's easier to notice that the scale has changed. Tank you for the suggestions

**Comment by Bastian-5** [comment]
I'm sorry for being rude in my (still somewhat relavent) version of this issue. I was just a bit annoyed that I had the facilities to make another pool full of mana, but didn't because I didn't know I needed to. The hovering thing still isn't a perfect solution, as it still leaves cases like mine where the user doesn't realize hovering over is necessary (or in my particular case, are too tired to actually read the zoom numbers correctly, or something, I don't remember. I accept it was partially my fault, but it's also part of your responsibility* to prevent Murphy's Law), as there is nothing else I am aware of that costs more than a full pool of mana that is displayed in the book. The mana gauge is useful only if it can show within 1 mana pool how much mana something costs. It would be significantly more useful to just go out and say that terasteel costs the normal infusion amount (although it'd be nice to get that at a slight discount considering the effort you have to go through to get the upgraded plate) and that the alfsteel costs 4x the amount that terasteel does (or just stating it costs 2 mana pools). Considering how easy of a change this would be, and the considerable headaches it would save, please consider implementing something to actively warn the player that it costs 2 mana pools, instead of just leaving it up to us to check that the cost shown on the surface is accurate.

*yes, you are not logically capable of reaching an aught statement without another aught statement, however here I'm assuming you are following the aught statement of "I aught to make this as good as I can", from which would eventually follow an aught statement of preventing Murphy's Law through a chain of logic I do not wish to document here.

**Comment by noeppi-noeppi** [comment]
Yea I already addressed the problem and uploaded a version earlier this day, that shows the amount of mana in pools when using JEI (`2 Mana Pools` or `0.5 Mana Pools`) and in the lexicon I made the zoomed out mana bar the default. You can now zoom in by hovering the mana bar. I hope this helps players to understand the mana cost better. If there's anything else I should do in your optinion, let me know.
