### ISSUE TITLE
Cannot place Mjöllnir while it is on cooldown

### ISSUE THREAD

**Issue by Wxrlds** [noeppi-noeppi/MythicBotany#39]
Title says it all although I don't know if that's intended behaviour.
Reproduce this by eating a golden apple, throwing Mjöllnir and picking it up before the cooldown ends, then attempt to place it in the world with sneak + place.

Mods used:
MythicBotany-1.16.4-1.3.2.jar
Minecraft: 1.16.5
Forge: 36.1.16
Botania-1.16.5-415.jar
curios-forge-1.16.5-4.0.5.1.jar
jei-1.16.5-7.6.4.87.jar
LibX-1.16.3-1.0.60.jar
Patchouli-1.16.4-50.jar

**Comment by noeppi-noeppi** [comment]
This is due to the cooldown tracker preventing any interaction. There's no easy way for me to fix this and as it's not a serious bug, I won't fix it. Why should you even place the hammer down in a fight... And if it's not a fight you can just wait that little time. If minecraft changes how the cooldown tacker works in the future, the bug will be fixed but for now it will not.
