### ISSUE TITLE
client world renderer issue (server crash - server/client disconnect)

### ISSUE THREAD

**Issue by jkwphysics** [noeppi-noeppi/MythicBotany#74]
Updated this mod to 1.4.0 and my server stopped allowing players to connect.

```
[08Aug2021 00:14:49.890] [main/FATAL] [net.minecraftforge.fml.loading.RuntimeDistCleaner/DISTXFORM]: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER
[08Aug2021 00:14:49.891] [main/WARN] [mixin/]: Error loading class: net/minecraft/client/renderer/WorldRenderer (java.lang.RuntimeException: Attempted to load class net/minecraft/client/renderer/WorldRenderer for invalid dist DEDICATED_SERVER)
[08Aug2021 00:14:49.892] [main/WARN] [mixin/]: @Mixin target net.minecraft.client.renderer.WorldRenderer was not found mythicbotany.mixins.json:MixinWorldRenderer
```

I tried rolling it back... and something is corrupted.  Might be an issue with Forge 36.2.0? Right now I cannot enter the server world, nor the backup world with the previous version.
`
Server thread/ERROR [minecraft/ServerRecipeBook]: Tried to load unrecognized recipe: mythicbotany:alfsteel  [ etc... ]
`

I tried removing the mod entirely, and I still cannot get a client to connect to the server.  The FATAL error no longer occurs without the mod, but clients that were previously connected with MythicBotany can't connect to the server... I think the only thing I can do is wipe the world unfortunately since they can connect to a new world without the mod....

**Comment by Sunconure11** [comment]
Are you using Mohist?

I got a similar issue with Mohist.

https://pastebin.com/G0Ta0gy0

**Comment by Sunconure11** [comment]
@noeppi-noeppi

**Comment by noeppi-noeppi** [comment]
That issue should only occur if another mod messes sth up. I'll make the mixin be only applied on the client which should remove that error message.

And @Sunconure11 the issue you mention is different. It's because [this](https://github.com/tasgon/observable/blob/master/common/src/main/java/observable/mixin/ServerLevelMixin.java#L18-L27) mixin is incompatible with [this](https://github.com/MohistMC/Mohist/blob/1.16.5/patches/minecraft/net/minecraft/world/server/ServerWorld.java.patch#L529-L542) mohist patch which moves the `tick` method invocation into a lambda. That makes the observable mixin unable to find the call and redirect it.
LibX has a mixin for fluid ticks but it does not seem to be affected by this issue.
